import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import Head from "next/head";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <title>
          Корейские автомобили Hyundai, Kia, Genesis — каталог моделей и цены
        </title>
        <meta
          name="description"
          content="Обзор корейских автомобилей: Hyundai, Kia, Genesis, SsangYong. Характеристики, цены, фото, отзывы. Каталог авто из Южной Кореи."
        />

        <meta
          name="keywords"
          content="корейские автомобили, Hyundai, Kia, Genesis, SsangYong, авто Южной Кореи, каталог машин"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Noto+Sans:wght@400;600;700&display=swap"
          rel="stylesheet"
        />
      </Head>

      <body className="min-h-screen flex flex-col   mx-auto ">
        <h1 className="absolute -left-9999999">
          Авто из кореи под заказ Автомобили из Южной Кореи: Hyundai, Kia,
          Genesis, SsangYong, BMW, Mercedes-Benz, Audi, Volkswagen — каталог
          моделей, цены, характеристики
        </h1>
        <Header />
        <main className="flex-grow min-h-[70vh]">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
